---
#- name: install cri-o packages
#  dnf: name={{ item }} state=present
#  with_items:
#    - cri-o

# TASK [container : set insecure registry]
# *******************************************************************************************************************
# fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}

- name: install docker packages
  dnf: name={{ item }} state=present
  with_items:
    - docker
    - libselinux-python

- name: check for insecure registry
  shell: grep insecure-registry /etc/sysconfig/docker
  register: insecure_registry_present
  failed_when: "insecure_registry_present == 2"
  changed_when: false

- name: set insecure registry
  lineinfile:
    path: /etc/sysconfig/docker
    regexp: "^(OPTIONS=.*)'$"
    line: "\\1 --insecure-registry 172.30.0.0/16'"
    backrefs: yes
    backup: yes
  when: insecure_registry_present.rc|int == 1

- name: start docker service
  systemd:
    name: docker
    state: restarted
    enabled: yes
