---
- name: install basic packages
  dnf: name={{ item }} state=present
  with_items:
    - zsh
    - git
    - keepassx
    - libselinux-python
    - docker
    - virt-manager
    - libvirt-daemon-config-network
    - strace
    - nmap
    - i3
    - i3lock
    - i3blocks
    - screen
    - libvirt-client
    - feh
    - xcompmgr
    - xbacklight
    - pulseaudio
    - firewall-config
    - tuned
    - lm_sensors
    - acpi
    - sysstat

- name: check for atom packages
  dnf: name=atom state=present
  register: atom_installed
  ignore_errors: True

- name: install atom
  dnf: name=https://github.com/atom/atom/releases/download/v{{atom_version}}/atom.x86_64.rpm state=present
  when: atom_installed|failed

- name: start basic services
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - libvirtd
    - tuned
