---
- name: update installed packages
  dnf:
    name: "*"
    state: latest

- name: install basic packages
  dnf: name={{ item }} state=present
  with_items:
    - zsh
    - git
    - keepassx
    - libselinux-python
    - virt-manager
    - libvirt-daemon-config-network
    - strace
    - nmap
    - screen
    - libvirt-client
    - feh
    - xcompmgr
    - xbacklight
    - pulseaudio
    - firewall-config
    - tuned
    - lm_sensors
    - acpi
    - sysstat
    # - nitrokey-app
    - p7zip
    - powertop
    - lsyncd
    - vim-enhanced
    - tcpdump
    - tlp
    # - chromium
    - rxvt-unicode
    - golang
    - krb5-workstation
    - hexchat
    - minicom
    - systemtap
    - pantheon-files
    - lightdm

# sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
# sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
- name: import M$ vscode RPM key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: set vscode repo def filepath
  set_fact: vscode_repo_def=/etc/yum.repos.d/vscode.repo

- name: Check that vscode repo def file exists
  stat:
    path: "{{ vscode_repo_def }}"
  register: vscode

- name: Create vscode repo def file
  file:
    path: "{{ vscode_repo_def }}"
    state: touch
  when: vscode.stat.exists == False

- name: create Yum repo definition
  blockinfile:
    path: "{{ vscode_repo_def }}"
    block: |
      [code]
      name=Visual Studio Code
      baseurl=https://packages.microsoft.com/yumrepos/vscode
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc

- name: install Visual Studio Code
  dnf: name=code state=present

# - name: check for atom packages
#   dnf: name=atom state=present
#   register: atom_installed
#   ignore_errors: True

# - name: install atom
#   dnf: name=https://github.com/atom/atom/releases/download/v{{atom_version}}/atom.x86_64.rpm state=present
#   when: atom_installed|failed

- name: start basic services
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - libvirtd
    - tuned

- name: disable gdm
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - gdm

- name: enable lightgdm
  service: name={{ item }} state=started enabled=yes
  with_items:
    - lightdm
