---
- name: set swappiness
  lineinfile:
    path: /etc/sysctl.d/60-swappiness.conf
    create: yes
    regexp: '^vm.swappiness='
    line: 'vm.swappiness=1'
    backup: yes

#- name: set Kyber I/O scheduler for SSD
#  lineinfile:
#    path: /etc/udev/rules.d/60-iosched.rules
#    regexp: '.*="kyber"$'
#    line: 'ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="kyber"'
#    backup: yes

- name: set BFQ I/O scheduler
  lineinfile:
    path: /etc/udev/rules.d/60-iosched.rules
    create: yes
    regexp: '.*="bfq"$'
    line: 'ACTION=="add|change", KERNEL=="nvme[0-9a-z]*", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"'
    backup: yes


# include kyber, bfq and udev rules in initramfs - use handler b/c fstrim also requires rebuild of initramfs
# --force-drivers bfq --force-drivers kyber-iosched --install "/etc/udev/rules.d/60-iosched.rules"

#
#[torben@tower ~]$ cat /etc/modprobe.d/blacklist.conf 
#blacklist nouveau
#[torben@tower ~]$ grep nouveau /etc/sysconfig/grub
#GRUB_CMDLINE_LINUX="rd.lvm.lv=fedora00/swap rhgb quiet rd.driver.blacklist=nouveau scsi_mod.use_blk_mq=1 #rd.luks.options=discard"
#[torben@tower ~]$ 

