---
- name: update installed packages
  dnf:
    name: "*"
    state: latest

- name: install basic packages
  dnf: name={{ item }} state=present
  with_items:
    - gluster-fuse
    - screen
    - zsh
...
