---
- name: install rpmfusion packages
  dnf: name={{ item }} state=present disable_gpg_check=true
  with_items:
    #- https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    #- https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-branched.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-branched.noarch.rpm

- name: install codecs
  dnf: name={{ item }} state=present
  with_items:
    - gstreamer1-libav
    - x264
    - h264enc
