---
- name: install glusterfs client packages
  dnf: name={{ item }} state=present
  with_items:
    - openssh-server
    - wget
    - fuse
    - fuse-libs
    #- openib
    - libibverbs
    - python3-firewall

