---
- name: restart NetworkManager
  systemd:
    state: restarted
    daemon_reload: yes
    name: NetworkManager
    enabled: yes
  listen: "restart_nm"

- name: restart iptables
  # shell: iptables-restore </etc/sysconfig/iptables
  systemd:
    state: restarted
    daemon_reload: yes
    name: iptables
    enabled: yes
  listen: reload_iptables

- name: restart dnsmasq
  systemd:
    state: restarted
    daemon_reload: yes
    name: dnsmasq
    enabled: yes
  listen: restart_dnsmasq

- name: restart fail2ban
  systemd:
    state: restarted
    daemon_reload: yes
    name: fail2ban
    enabled: yes
  listen: restart_fail2ban
...
