- hosts: localhost
  connection: localhost
  vars:
    - atom_version: 1.21.0
  roles:
  - basic
  - { role: container, tags: ['tower'] }
  - { role: i3, tags: ['tower'] }
  - { role: trim, tags: ['tower'] }
  - { role: blk-mq, tags: ['tower'] }
  - { role: ovpn, tags: [] }
  - { role: mmedia, tags: [] }
  - { role: hw, tags: ['tower'] }
  - { role: nas, tags: ['tower'] }
  - { role: glusterfs-client, tags: ['tower','selected'] }

  # - { role: blk-mq, tags: ['new'] }
  # - nodejs
  # - google-cloud-sdk
