- hosts: localhost
  connection: localhost
  vars:
    - atom_version: 1.21.0
  roles:
  - { role: basic, tags: ['t450','tower'] }
  - { role: i3, tags: ['t450','tower'] }
  - { role: trim, tags: ['t450','tower'] }
  - { role: blk-mq, tags: ['t450','tower'] }
  - { role: hw, tags: ['t450','tower'] }
  - { role: glusterfs-client, tags: ['t450','tower'] }
  - { role: nas, tags: ['tower'] }
  - { role: nested-kvm, tags: ['selected'] }
  - { role: ovpn, tags: ['t450'] }
  - { role: mmedia, tags: ['t450'] }
  - { role: google-cloud-sdk, tags: ['t450'] }
  # - { role: container, tags: ['t450','tower'] }
  # - { role: blk-mq, tags: ['new'] }
  # - nodejs
