---
- hosts: localhost
  connection: localhost
  vars:
    - atom_version: 1.21.0
  handlers:
    - import_tasks: handlers.yml
  roles:
  - { role: basic, tags: ['t450','tower'] }
  # - { role: i3, tags: ['t450','tower'] }
  - { role: sway, tags: ['t450','tower'] }
  - { role: trim, tags: ['t450','tower'] }
  - { role: blk-mq, tags: ['t450','tower'] }
  - { role: hw, tags: ['t450','tower'] }
  - { role: glusterfs-client, tags: ['t450','tower', 'gluster'] }
  - { role: nas, tags: ['tower', 'nas'] }
  - { role: nested-kvm, tags: [] }
  - { role: ovpn, tags: ['t450'] }
  - { role: mmedia, tags: ['t450'] }
  - { role: google-cloud-sdk, tags: ['t450'] }
  # - { role: minishift, tags: ['t450', 'minishift'] }
  - { role: nm, tags: ['t450', 'tower', 'nm'] }
  # - { role: container, tags: ['t450','tower'] }
  # - { role: blk-mq, tags: ['new'] }
  # - nodejs
...
