---
- name: install basic packages
  dnf: 
    state: present
    name: 
      # dwm make
      - xfce4-terminal
      - dmenu
      - make
      - libX11-devel
      - libXft-devel
      - libXinerama-devel
...
