---
- name: install basic packages
  dnf: 
    state: present
    name: 
      # dwm make
      - xfce4-terminal
      - dmenu
      - make
      - libX11-devel
      - libXft-devel
      - libXinerama-devel
      - zsh
      - redhat-rpm-config
      - libva-intel-driver
      - xorg-x11-drv-intel

- name: install xorg intel driver
  debug: 
    msg: "install files/20-intel.conf"
...
