---
- name: create Google Cloud SDK repo file
  template: src=google-cloud-sdk.repo.j2 dest=/etc/yum.repos.d/google-cloud-sdk.repo owner=root group=root mode=0644

- name: install Google Cloud SDK
  dnf: name={{item}} state=present
  with_items:
    - google-cloud-sdk
